class ProfileHelper {
  List<String> interests = [
    'Reading',
    'Movies',
    'Hiking',
    'Art',
    'Photography',
    'Cooking',
    'Running',
    'Yoga',
    'Technology',
    'Fashion',
    'Nature',
    'Cycling',
    'Meditation',
    'Foodie',
    'Dancing',
    'Theatre',
    'Volunteering',
    'Gaming',
    'Podcasts',
    'Gardening',
    'Writing',
    'Traveling (alternative spelling)',
    'Coffee',
    'Beaches',
    'Board Games',
  ];

  List<String> zodiacSigns = [
    'Aries',
    'Taurus',
    'Gemini',
    'Cancer',
    'Leo',
    'Virgo',
    'Libra',
    'Scorpio',
    'Sagittarius',
    'Capricorn',
    'Aquarius',
    'Pisces',
  ];
}
