// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFxfjioEfvrGaQvn8kRA0X7ncOTZ5mD40',
    appId: '1:502306764854:web:aea0e3371d68ee1380c097',
    messagingSenderId: '502306764854',
    projectId: 'matchster-53774',
    authDomain: 'matchster-53774.firebaseapp.com',
    storageBucket: 'matchster-53774.firebasestorage.app',
    measurementId: 'G-0M5CBEJEMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATfwQTWSyU7bVz1GKqBHwH8KwANxDUPHY',
    appId: '1:502306764854:android:06200033dca6fd0f80c097',
    messagingSenderId: '502306764854',
    projectId: 'matchster-53774',
    storageBucket: 'matchster-53774.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDghf9IgUpHSM0TUNXDhpkoOT_0JcdX11U',
    appId: '1:502306764854:ios:13e22781f071423580c097',
    messagingSenderId: '502306764854',
    projectId: 'matchster-53774',
    storageBucket: 'matchster-53774.firebasestorage.app',
    iosBundleId: 'com.matchster.matchster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDghf9IgUpHSM0TUNXDhpkoOT_0JcdX11U',
    appId: '1:502306764854:ios:13e22781f071423580c097',
    messagingSenderId: '502306764854',
    projectId: 'matchster-53774',
    storageBucket: 'matchster-53774.firebasestorage.app',
    iosBundleId: 'com.matchster.matchster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFxfjioEfvrGaQvn8kRA0X7ncOTZ5mD40',
    appId: '1:502306764854:web:f33bb227f43ed1d880c097',
    messagingSenderId: '502306764854',
    projectId: 'matchster-53774',
    authDomain: 'matchster-53774.firebaseapp.com',
    storageBucket: 'matchster-53774.firebasestorage.app',
    measurementId: 'G-T66JRG947T',
  );
}
