class AppRoutes {
  static const splashScreen = '/splash_screen',
      onboardScreen = '/onboard_screen',
      landingScreen = '/landing_screen',
      verifyEmailScreen = "/verify_email_screen",
      currentLoadingScreen = "/current_loading_screen",
      profilePreviewScreen = "/profile_preview_screen",
      currentLocation = "/current_location",
      addHomeTownScreen = "/add_home_town_screen",
      setting = "/setting",
      verifyEmailOtpScreen = "/verify_email_otp_screen",
      locationSearchScreen = "/location_search_screen",
      heightScreen = "/height_screen",
      educationScreen = "/education_screen",
      workScreen = "/work_screen",
      zodiacScreen = "/zodiac_screen",
      religionScreen = "/religion_screen",
      visibilityScreen = "/visibility_screen",
      lookingScreen = "/looking_screen",
      workoutScreen = "/workout_screen",
      smokeScreen = "/smoke_screen",
      alcohalScreen = "/alcohal_screen",
      interestScreen = "/interest_screen",
      languagesScreen = "/languages_screen",
      loginFieldScreen = "/login_field_screen",
      loginScreen = '/login_screen';
}
